### ISSUE TITLE
Last updated 4 months ago? Keep going, mate!

### ISSUE THREAD

**Issue by thi-days** [mvrsdev/02-loginpage#1]

**Comment by mvrsdev** [comment]
I'm geting my ass kicked by that landing page project hahahaha but I think today I'll finally resolve it. It's open already
![Screen Shot 2022-02-16 at 12 01 51](https://user-images.githubusercontent.com/93167052/154292474-62d24de1-10b1-4e29-a79f-67558d2d9b03.png)
